version: '3'

services:
  django:
    build: ./Backend/GO_Intern_backend
    volumes:
      - ./Backend/GO_Intern_backend:/app
    ports:
      - "8000:8000"

  react:
    build: ./Frontend/GO_Intern_Frontend
    volumes:
      - ./Frontend/GO_Intern_Frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - django  