version: '3'

services:
  django:
    build: ./Backend/GO_Intern_backend
    ports:
      - "8000:8000"

  react:
    build: ./Frontend/GO_Intern_Frontend
    ports:
      - "3000:3000"
    depends_on:
      - django
